main: community.leaf.survival.concretemixer.ConcreteMixerPlugin
name: ${project.name}
version: ${project.version}
api-version: 1.17
softdepend: [GriefPrevention]

authors: [RezzedUp]
description: ${project.description}
website: ${project.url}
