main: community.leaf.survival.concretemixer.ConcreteMixerPlugin
name: ${project.name}
version: ${project.version}
api-version: 1.13
softdepend: [GriefPrevention, WorldGuard]

authors: [RezzedUp]
description: ${project.description}
website: ${project.url}
